// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFrzWZpbHJ0LQh62PFcCsKDXUBW1oW1iE',
    appId: '1:1026134323276:web:859a0f25c770051d7f04e9',
    messagingSenderId: '1026134323276',
    projectId: 'tien-dien-28d7a',
    authDomain: 'tien-dien-28d7a.firebaseapp.com',
    storageBucket: 'tien-dien-28d7a.firebasestorage.app',
    measurementId: 'G-YTEXJJ2H80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuHI-C9lhY0dTfCnILBIHshzvURswUohI',
    appId: '1:1026134323276:android:ba2fdc51b38057b57f04e9',
    messagingSenderId: '1026134323276',
    projectId: 'tien-dien-28d7a',
    storageBucket: 'tien-dien-28d7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMO_VfvC_rWUR1RBFbcL7Fn4pBKacG708',
    appId: '1:1026134323276:ios:366cbd5331c5f5e37f04e9',
    messagingSenderId: '1026134323276',
    projectId: 'tien-dien-28d7a',
    storageBucket: 'tien-dien-28d7a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMO_VfvC_rWUR1RBFbcL7Fn4pBKacG708',
    appId: '1:1026134323276:ios:366cbd5331c5f5e37f04e9',
    messagingSenderId: '1026134323276',
    projectId: 'tien-dien-28d7a',
    storageBucket: 'tien-dien-28d7a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFrzWZpbHJ0LQh62PFcCsKDXUBW1oW1iE',
    appId: '1:1026134323276:web:2a6282c915698a707f04e9',
    messagingSenderId: '1026134323276',
    projectId: 'tien-dien-28d7a',
    authDomain: 'tien-dien-28d7a.firebaseapp.com',
    storageBucket: 'tien-dien-28d7a.firebasestorage.app',
    measurementId: 'G-5Q2FTW8W7C',
  );
}
